import "./globals.css";
import type { Metadata } from "next";
import { Karla, Micro_5 } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const karla = Karla({
  variable: "--font-karla",
  subsets: ["latin"],
});

const micro5 = Micro_5({
  variable: "--font-micro5",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Kevin Thomas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${karla.variable} ${micro5.variable} bg-black antialiased`}
      >
        <div className="mx-auto flex min-h-screen max-w-[1280px] flex-col items-center">
          <Header />
          <main className="border-border w-full border">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
